profile: ambient
image: yunacr.azurecr.io/pilot:1.29.0-hbone-envvars
global:
  imagePullPolicy: Always
pilot:
  env:
    ENABLE_INGRESS_WAYPOINT_ROUTING: true
    PILOT_ENABLE_ALPHA_GATEWAY_API: true
    #PILOT_HTTP10: true
    PILOT_HBONE_INITIAL_STREAM_WINDOW_SIZE: 65535
    PILOT_HBONE_INITIAL_CONNECTION_WINDOW_SIZE: 262140
meshConfig:
  defaultConfig:
    proxyStatsMatcher:
      inclusionRegexps:
        - ".*"
  discoverySelectors:
    - matchLabels:
        istio-discovery: enabled
  hboneIdleTimeout: 15s
